### ISSUE TITLE
Practica Contrato

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/contrato-de-software-entrevista-tr#1]
[Practica Contrato.pdf](https://github.com/SistemasTecTlaxiaco/contrato-de-software-entrevista-tr/files/7737654/Practica.Contrato.pdf)

**Comment by dulce-blm** [comment]
Calificación: 20 puntos 
Contiene las clausulas establecidas, es claro y preciso, además de contener lo necesario dentro de ello la firma de la empresa desarrolladora y la empresa cliente.

**Comment by Brendalp** [comment]
calificación en la wiki= 80

**Comment by josealfredo79** [comment]
Bien hecho y revisado
